# render.yaml

services:
  # — your managed Postgres
  - type: database
    name: fortrying-db
    plan: starter
    region: oregon
    databaseName: fortrying_prod

  # — your FastAPI backend, built from backend/Dockerfile
  - type: web
    name: fortrying-backend
    env: docker
    dockerfilePath: backend       # ← point at the folder containing your Dockerfile
    buildCommand: docker build -f Dockerfile -t fortrying-backend . 
    # Render will run this inside the `backend/` dir
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase: fortrying-db
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: CORS_ORIGINS
        value: https://fortrying.onrender.com
    healthCheckPath: /health

  # — your Next.js frontend as a static site
  - type: web
    name: fortrying-frontend
    env: static
    buildCommand: |
      cd frontend
      npm ci
      npm run build && npm run export
    staticPublishPath: frontend/out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://fortrying-backend.onrender.com
