"""Add IP and user-agent to address audit logs

Revision ID: a80a71a89dfe
Revises: 437ef1347500
Create Date: 2025-05-11 10:06:40.093495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80a71a89dfe'
down_revision: Union[str, None] = '437ef1347500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_audit_logs', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('address_audit_logs', sa.Column('user_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_audit_logs', 'user_agent')
    op.drop_column('address_audit_logs', 'ip_address')
    # ### end Alembic commands ###
