"""Add orders and order_items

Revision ID: fd6961fcbfa4
Revises: dcab3b20060f
Create Date: 2025-05-09 20:22:14.843846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd6961fcbfa4'
down_revision: Union[str, None] = 'dcab3b20060f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_images_id', table_name='product_images')
    op.drop_table('product_images')
    op.alter_column('cart_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'])
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'payment_status')
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.add_column('orders', sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('product_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='product_images_pkey')
    )
    op.create_index('ix_product_images_id', 'product_images', ['id'], unique=False)
    # ### end Alembic commands ###
